version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 12
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Testing the image
      - npm run build
      - echo Building the image
      - docker tag $IMAGE_NAME:IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/
      $IMAGE_NAME:IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:IMAGE_TAG
      - printf '[{"name":"%s","imageUrl":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json